export enum EnvName {
  DB_DIALECT = "DB_DIALECT",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD",
  DB_NAME = "DB_NAME",
  DB_POOL_MAX = "DB_POOL_MAX",
  DB_POOL_MIN = "DB_POOL_MIN",
}
