apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-web
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
    - host: "huddle.fun"
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: web-cluster-ip-service
                port:
                  number: 3000
