apiVersion: v1
kind: Service
metadata:
  name: test-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: test-service
  ports:
    - port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test-service
  template:
    metadata:
      labels:
        component: test-service
    spec:
      containers:
        - name: test-service
          image: huddle-test-service-dev
          ports:
            - containerPort: 4000
          env:
            - name: ISSUER_BASE_URL
              value: "https://dev-btucf4rv42ikfl83.us.auth0.com"
            - name: AUDIENCE
              value: "api.huddle.fun/test"
