apiVersion: v1
kind: Service
metadata:
  name: web-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web-service
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web-service
  template:
    metadata:
      labels:
        component: web-service
    spec:
      containers:
        - name: web-service
          image: huddle-web-service-dev
          ports:
            - containerPort: 3000
          env:
            - name: AUTH0_SECRET
              value: "36d27b8478d28bd60af4eaa3b15755f1541f90da9a3150c3b42455064f4af333"
            - name: AUTH0_BASE_URL
              value: "http://huddle.fun"
            - name: AUTH0_ISSUER_BASE_URL
              value: "https://dev-btucf4rv42ikfl83.us.auth0.com"
            - name: AUTH0_CLIENT_ID
              value: "Sl9UCPHMiOmMx0nEYWvJCIEhNnjkvrHk"
            - name: AUTH0_CLIENT_SECRET
              value: "ZYD_hhiPmKYcuxgCOi112nzDKbJBn7dyYvrjH91P6kfdy_PxZKSEmao_cbc0EoPd"
            - name: AUTH0_AUDIENCE
              value: "api.huddle.fun/test"
            - name: AUTH0_SCOPE
              value: "openid profile create:book"
